### PR TITLE
updated debian 7.0 rc1 to 7.1.0

### PR DESCRIPTION
**Pull request by russkel**
I didn't touch the vmware fusion files as I do not own vmware fusion and cannot test.

### CODE REVIEW

**Comment by kbarber** [comment]
+1 @russkel ... I'll be re-rolling the images soonish, and will look at this patch at that point.

**Comment by EmmanuelKasper** [comment]
Thanks for taking this in account.

**Comment by kbarber** [comment]
Looks like Debian 7.1.0 was released 2013/6/15, I'm going to target that instead.

**Comment by russkel** [comment]
No kidding. All that hard work for nothing ;).

**Comment by kbarber** [comment]
Not for nothing, I'm copying the 7.0 template over and will raise that with upstream veewee once done (probably in an hour or so - if all my tests pass) - so its all good :-). Whats weird is the cdimage isn't even available for 7.0 from my local mirrors anymore, I think there was a security issue with the older version of some kind.

**Comment by russkel** [comment]
Updated my VPS, lots of updates! Looks like there was some rather serious issues.

Anyway, I updated the pull req, just in case you haven't done so yet.

Edit: :sob: Sorry, I just re-read the readme on this project and you clearly state you want bugfixes sent upstream to veewee. I didn't see that the first time around.

**Comment by russkel** [comment]
@puppetcla I believe this falls under trivial fixes as it is "Changes to ‘metadata’ files like Gemfile, .gitignore, example configuration files, build scripts, etc."

I tried to sign it anyway as an individual, but I'm getting gateway timeout errors.

**Comment by 3flex** [comment]
veewee has a Debian 7.2 template, as well as updated templates for Debian 7.1 with corrected URLs to the ISO (older versions are put into an archive folder) and a message for Debian 7.0 users advising where they can manually download the ISO via bittorrent or jigdo (the ISO itself is no longer hosted).

Suggest updating the templates here and rolling out updated Debian images.

**Pull request closed without merging**
