### PR TITLE
WIP: Built new definitions based on updated veewe templates

### PR DESCRIPTION
**Pull request by eshamow**
Renamed baseboxes to fit more specific naming scheme based on discussion
with kbarber.  All other changes pushed upstream to veewee project and then
copied back here.

### CODE REVIEW

**Comment by kbarber** [comment]
You shouldn't be renaming the existing definitions. Once boxes are built they are locked in and one shouldn't be changing them. You should instead be creating new definitions with the new naming conventions.

**Comment by eshamow** [comment]
Ken,

The old box definitions no longer work, since URLs have changed.  Since I recopied the stuff from upstream to preserve compatibility, I thought it best to rename immediately to signal the change.

Am I better off leaving the old (broken) templates alongside new ones, with new names, that work?

**Comment by kbarber** [comment]
@eshamow so if the old definitions no longer work due to broken urls, they can be fixed if required. But new images should have new definitions. Just create new definitions for your new work, and optionally update the old definitions with the new urls if you desire it, but since the boxes are already built its not a big requirement.

Again, the definitions are a copy of how the definition at box build time. There should be a one to one mapping between box and definition. Since you are creating new boxes, create new definitions.

**Comment by eshamow** [comment]
OK that makes sense @kbarber.  I will rebase my branch and update here when that is done.

## 

Eric Shamow
Puppet Labs

**Comment by eshamow** [comment]
@kbarber Old changes reverted and mixed with new - you can tell the new defs by name now, but the old are left alone.

**Comment by kbarber** [comment]
@eshamow is ubuntu 12.04.2 available in veewee 0.3.7? Are you working from master?

**Comment by eshamow** [comment]
@kbarber Nope, but none of the current distro versions are, and the ones that ARE in 0.3.7 don't work as a result - they point to "current" directories rather than the actual directories for the ISOs, and a few break with the new vbox tools, etc.

My choices are either to copy from 0.3.7 definitions and then modify heavily to make them work, or copy from master where we can at least track changes.

**Comment by kbarber** [comment]
Yeah, lets switch our Gemfile to use the github 'master' version then until we get a release and go ahead with your 5.9 and 12.04.2. If we need it now, we need it now. Also - btw - you need to update the index.html that will eventually be hosted on cloudfront. Probably need to reformat it a tad to list the old images as deprecated or some such. Maybe a table?

**Pull request closed without merging**
