### PR TITLE
KVM/libvirt support with vanilla image definitions

### PR DESCRIPTION
**Pull request by domcleal**
Includes new image definitions without VirtualBox or VMware build steps added, so as to create vanilla OS images that can be booted under KVM.

---

Just so you get the gist of what's needed for https://github.com/puppetlabs/rspec-system/issues/18 more than anything.  The definitions are more or less just copies of the others that are there (except the Debian 7.0 one, which was from veewee).

### CODE REVIEW

**Comment by kbarber** [comment]
Hi @domcleal thanks for the patch :-).

Are these changes already reflected in veewee upstream? I'm avoiding upstream divergence here, and I've been making sure any changes I provide are reflected in the upstream. In the future these local copies of definitions will go away and be auto-generated from upstream anyway. And if you get it into upstream a greater audience will benefit.

Also whats the logic around KVM images having no virt type declaration in the name? I'm not sure I agree with presuming KVM or this image format is the default or non-special case here.

**Comment by kbarber** [comment]
Further to this, I didn't really have a closer look, but perhaps these definitions are just the base ones anyway right? I presume nothing special needs to be done on your average Linux KVM guest these days. I presume the definition.rb files were just modified? Alas this is the difficulty with the current process - its hard to tell at a glance which is why I need to fix it.

Also I notice Centos 5.9 and Ubuntu 10.04 are not included here. Is there a problem with building these on KVM?

On a related note I'm really keen to get KVM hosted, like you I want them for `rspec-system` so we get better traction with Linux users. I'm developing better automation around this process as we speak actually - I'm in the process of rebuilding all the virtualbox/fusion images this week using this improved process. I'd love to get KVM in the process, in fact its going to be easier then fusion (since fusion means I need a mac jenkins slave which I lack atm).

**Comment by domcleal** [comment]
Indeed, there are a couple of changes from upstream, I'll work on merging those there first.  IIRC it's around disk selection, removing hardcoded references to 'sda'.

You're right that apart from those fixes (which aren't KVM-specific), the images are just the base veewee templates, no extras, which is why I didn't append a virt type suffix.  Clearly the resulting boxes would be KVM-specific due to the format and installations themselves, so we could keep it in the box name just to be clear if you'd prefer.

Perhaps just using the base templates and then the -i/-e options to veewee foo build would allow you to add/remove VMware or vbox agents from the process?

Regarding CentOS 5.9 and Ubuntu 10.04, I simply didn't need them.  I don't anticipate any issues, will add them to my next update.

**Comment by domcleal** [comment]
The changes have been swiftly merged in upstream, as have yours I notice.  I'll hold off updating this until you've got your refresh in, then rebase.

**Comment by kbarber** [comment]
The images so far in their temp CI locations:

http://puppet-vagrant-boxes-ci.s3.amazonaws.com/centos-64-x64-kvm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/centos-64-x64-kvm-nocm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/debian-607-x64-kvm-3.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/debian-607-x64-kvm-nocm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/debian-710-x64-kvm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/debian-710-x64-kvm-nocm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/scientificlinux-64-x64-kvm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/scientificlinux-64-x64-kvm-nocm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/ubuntu-server-10044-x64-kvm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/ubuntu-server-10044-x64-kvm-nocm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/ubuntu-server-12042-x64-kvm-2.box
http://puppet-vagrant-boxes-ci.s3.amazonaws.com/ubuntu-server-12042-x64-kvm-nocm-2.box

I'll need to go through and test each one before publishing with Vagrant. @domcleal if you have any time, feel free to test some of them (I know you already tested 1). I'm just firing them up with vagrant and making sure puppet works (where applicable), I can sudo and the share directory exists etc.

We need to automate this testing I know :-). At the very least I have a Vagrantfile that does some of the heavy lifting:

<pre>
Vagrant.configure("2") do |config|
  # CI boxes
  box_names = [
    "centos-64-x64-vbox-45",
    "centos-64-x64-vbox-nocm-45",
    "centos-59-x64-vbox-47",
    "centos-59-x64-vbox-nocm-45",
    "debian-607-x64-vbox-45",
    "debian-607-x64-vbox-nocm-45",
    "debian-710-x64-vbox-45",
    "debian-710-x64-vbox-nocm-47",
    "scientificlinux-64-x64-vbox-45",
    "scientificlinux-64-x64-vbox-nocm-47",
    "ubuntu-server-10044-x64-vbox-47",
    "ubuntu-server-10044-x64-vbox-nocm-47",
    "ubuntu-server-12042-x64-vbox-47",
    "ubuntu-server-12042-x64-vbox-nocm-45",
  ]
  box_names.each do |box_name|
    config.vm.define box_name do |c|
      c.vm.box = box_name
      c.vm.hostname = box_name + ".vm"
      c.vm.box_url = "https://s3-eu-west-1.amazonaws.com/puppet-vagrant-boxes-ci/#{box_name}.box"
    end
  end
end
</pre>

**Comment by domcleal** [comment]
Both Scientific Linux images haven't had 70-persistent-net.rules cleared, so eth0 doesn't start and get an IP address.

My tests broke on Debian 6.0 nocm, but that appears to be my fault, assuming that a certain rubygem version is present that creates binstubs.  The box with CM tools installed gets the newer Ruby version due to Chef.

I've tested all of the rest except the Ubuntu 10.04 images (my tests need 12.04) and they're good, the Foreman tests all pass.

Any chance of adding a Fedora 18 prefab too?  Thanks!

**Comment by kbarber** [comment]
@domcleal completely forgot Fedora 18 for all the virts. Doh! I've noticed the scientificlinux problem already, I've got a patch for upstream I'll submit soon. Thanks Dom, btw - what plugin are you using with vagrant? vagrant-kvm throws an exception for me, and vagrant-libvirt throws a segfault. I'm testing on Debian 7.0, not sure why it happens yet.

**Comment by domcleal** [comment]
Sounds good, thanks.  I'm using vagrant-libvirt and haven't hit any segfaults (on F18)!  Vagrant provides its own Ruby as well (at least in the RPMs) so I'm surprised it's only hitting one of us.

**Comment by ekohl** [comment]
Any progress on this?

**Comment by domcleal** [comment]
Closing, I no longer use these boxes, preferring the official distro boxes in Vagrant Atlas instead.

**Pull request closed without merging**
