### PR TITLE
WIP: New boxes

### PR DESCRIPTION
**Pull request by eshamow**
Adds support for the new full set of boxes (all PE platforms at their latest versions) including nocm builds, without Puppet, Chef or Ruby pre-installed and in both x86_64 and i386 versions.

These are all accepted upstream at veewee.

### CODE REVIEW

**Comment by kbarber** [comment]
@eshamow this needs to be rebased.

Also - can you update the README.md to reflect the new naming conventions? Its now completely different.

**Comment by kbarber** [comment]
Come to think of it, I have a problem with the naming convention.

Debian-6.0.7-etc.etc. ... produces a hostname of 'Debian-6'. In /etc/hosts ... its hostname is 'Debian-6.0.7-amd64-netboot'. Notice the dots here and what it does? I warned about this in the README.md ... which is why I chose a specific naming convention in the first place.

**Comment by eshamow** [comment]
@kbarber Fair point re naming convention...sorry I missed that in README.  I tried to maintain the veewee convention despite its inconsistencies in order to make it easier to map these to their original profiles.

I'll rebase, add README updates, and renames.

**Comment by eshamow** [comment]
DON'T MERGE YET!  Rebased but now working on naming conventions.

**Pull request closed without merging**
