### PR TITLE
Solaris 10 Boxes

### PR DESCRIPTION
**Pull request by Sharpie**
Adds templates for rolling out Solaris 10 boxes. Providing pre-built boxes on S3 is problematic due to Oracle's licensing terms.

There are two custom patches that I didn't feel positive should be pushed upstream. The first installs the Vim editor. The second updates the terminfo definitions that ship with Solaris 10 by adding a definition for TERM=screen (also used by tmux) and TERM=xterm-256color (default on OS X 10.7 and newer). This keeps the default Solairs shell from completely freaking out if you happen to connect from a machine using one of those two terminal types.

### CODE REVIEW

**Comment by kbarber** [comment]
> Adds templates for rolling out Solaris 10 boxes. Providing pre-built boxes on S3 is problematic due to Oracle's licensing terms.

So to be very clear here, this project is not a set of alternate templates. Its just a record of what templates and their state was used to generate the ones on http://puppet-vagrant-boxes.puppetlabs.com. If we're not able to host them, then they don't belong here do they?

> There are two custom patches that I didn't feel positive should be pushed upstream. The first installs the Vim editor. The second updates the terminfo definitions that ship with Solaris 10 by adding a definition for TERM=screen (also used by tmux) and TERM=xterm-256color (default on OS X 10.7 and newer). This keeps the default Solairs shell from completely freaking out if you happen to connect from a machine using one of those two terminal types.

I'd rather we don't fork from upstream. Again, this is not a repository for hosting alternate templates.

**Comment by Sharpie** [comment]
> So to be very clear here, this project is not a set of alternate templates. Its just a record of what templates and their state was used to generate the ones on http://puppet-vagrant-boxes.puppetlabs.com.

Ok, that's a bit different than what I got from the first line of the README:

> This repository contains definitions and files necessary for recreating vagrant boxes suitable for running module tests with.

I took that to mean this was a place for publishing snapshots of veewee definitions that have been battled-tested for testing and debugging Puppet. From that point of view, it is handy to have templates for things like Solaris and Windows that we can't publish pre-built boxes for---but all users have to do is legally obtain the installation media and they can easily roll their own copy.

**Comment by kbarber** [comment]
> This repository contains definitions and files necessary for recreating vagrant boxes suitable for running module tests with.

I meant 'to recreate the boxes we host' ...

> I took that to mean this was a place for publishing snapshots of veewee definitions that have been battled-tested for testing and debugging Puppet. From that point of view, it is handy to have templates for things like Solaris and Windows that we can't publish pre-built boxes for---but all users have to do is legally obtain the installation media and they can easily roll their own copy.

Fair enough. Let me ponder this.

On the upstream note however, I would be surprised if they wouldn't accept your changes. At least the TERM one seems reasonable to me to be in upstream, if Mac clients can't connect to the image and do normal things, then the image needs to be patched.

This is similar to the mesg=n bug in Debian/Ubuntu, if you have this in your .profile then you get an error about 'stdin is not a tty' so the veewee templates generally patch this to remove the warning as it affects vagrant.

**Comment by kbarber** [comment]
@Sharpie having thought about this, I'm okay having the templates for Solaris & Windows here, even if we don't host. At least it gives a way to build consistent images, better then nothing.

So a few things then:
- Why i386?
- I would rather the TERM patch you made here been merged upstream - see my mesg example, but if you can explain why it shouldn't be I'm happy to hear it.

**Comment by Sharpie** [comment]
> Why i386?

As far as I can tell, Solaris 10 is only available for i386 and SPARC architectures.

> I would rather the TERM patch you made here been merged upstream - see my mesg example, but if you can explain why it shouldn't be I'm happy to hear it.

Sure thing. I didn't submit the TERM patch upstream for a rather dumb reason: It is a moderately quick hack that got the job done, but should be examined and re-done in a more careful manner.

I'll see about getting the TERM patch pushed upstream and will re-base this pull request when that task is finished.

**Comment by kbarber** [comment]
Sweet +1.

**Comment by kbarber** [comment]
@Sharpie hey mate. I saw your comment about vagrant + solaris the other day, nice find. How is this patch going you think? I'm probably going to start a re-rolling exercise soon (probably this weekend), and it would be fab to test this at that point to make sure its all good (and yes, I did just use the word 'fab').

**Comment by Sharpie** [comment]
Alright. Vim and terminfo patches finally submitted upstream: jedi4ever/veewee#733

**Comment by kbarber** [comment]
@Sharpie excellent work. Veewee is getting so much love from PL and the Puppet community lately it seems :-).

I'm rewriting the build process to be 'upstream only' to avoid all this confusion with the current 'definitions' dir - in short I'll just generate the definition when needed (although I'm still pondering the value of having the definition used stored somewhere?). I'm in the process of doing my refresh with that in mind, so a lot of this patch is not needed probably. Having said that, I want to leave this open as a reminder, and preserve the conversation.

Once I refresh all the existing linux boxes and iron out this new process, I'll probably test this build on its own targeting vbox, kvm, fusion and provide docs for users on how to do this themselves (as we can't host it).

I was thinking also - while I know we can't host this ourselves publicly (and I think SLES falls under this also - which I will probably need to drop), it might be valuable to have it available internally to PL at least. Not quite sure how, any ideas?

**Comment by Sharpie** [comment]
I'm going to go ahead and close this PR out as all of these tweaks are available upstream, plus a couple more. In the last few months I've been the only one making changes to the veewee Solaris 10 build, so there isn't enough activity to justify maintaining a "stable" snapshot here.

**Pull request closed without merging**
